create database chatfusion;
use chatfusion;

CREATE TABLE USER(USERID INTEGER AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(50), PHONE DECIMAL(10), PASSWORD VARCHAR(10), 
JOIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

SELECT * FROM USER;
TRUNCATE TABLE USER;

CREATE TABLE USER_ACCOUNTS(USERID INTEGER PRIMARY KEY, USERNAME VARCHAR(50), GENDER CHAR(1) NOT NULL DEFAULT '', 
IMAGE LONGBLOB, IMAGESTRING VARCHAR(255) DEFAULT '', STATUS CHAR(1) NOT NULL DEFAULT '1', FOREIGN KEY(USERID) REFERENCES USER(USERID) ON DELETE CASCADE);

SELECT * FROM USER_ACCOUNTS;
TRUNCATE TABLE USER_ACCOUNTS;

SELECT USERID, UA.USERNAME, GENDER, IMAGESTRING 
FROM USER JOIN USER_ACCOUNTS UA
USING (USERID) 
WHERE USER.USERNAME = BINARY('Subha') AND USER.PASSWORD = BINARY('123') AND UA.STATUS = '1';

CREATE TABLE FILES(FILEID INT PRIMARY KEY AUTO_INCREMENT, FileExtension varchar(255), BlurHash varchar(255), Status char(1) DEFAULT '0');

SELECT FileExtension FROM FILES WHERE FileID = 1 LIMIT 1;
SELECT * FROM FILES;
truncate table files;

CREATE TABLE CHATBOT_CONVERSATION(PROMPT VARCHAR(255), RESPONSE TEXT, UPLOAD_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP); 
select * from chatbot_conversation;
truncate table chatbot_conversation;