
package chatfusion.Chat.Forms;

import chatfusion.Chat.Event.EventMenuLeft;
import chatfusion.Chat.Event.PublicEvent;
import chatfusion.Model.Model_User_Account;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import net.miginfocom.swing.MigLayout;


public class Menu_Left extends javax.swing.JPanel {
    
    private List<Model_User_Account> userAccount;
    public Menu_Left() {
        initComponents();
        init();
    }
    
    private void init() {
        scrollpane.setVerticalScrollBar(new ScrollBar());
        chatList.setLayout(new MigLayout("fillx","1[]1","1[]1"));
        userAccount = new ArrayList<>();
        PublicEvent.getInstance().addEventMenuLeft(new EventMenuLeft() {
            @Override
            public void newUser(List<Model_User_Account> users) {
               for(Model_User_Account d : users) {
                   userAccount.add(d);
                   chatList.add(new ChatLayout(d), "wrap");
                   refreshChatList();
               } 
            }

            @Override
            public void userConnect(int userID) {
                for(Model_User_Account u : userAccount) {
                    if(u.getUserID() == userID) {
                        u.setStatus(true);
                        PublicEvent.getInstance().getEventMain().updateUser(u);
                        break;
                    }
                }
                if(msgMenuBtn.isSelected()) {
                    for(Component com : chatList.getComponents()) {
                        ChatLayout chat = (ChatLayout) com;
                        if(chat.getUser().getUserID() == userID) {
                            chat.updateStatus();
                            break;
                        }
                    }
                }
            }

            @Override
            public void userDisconnect(int userID) {
                for(Model_User_Account u : userAccount) {
                    if(u.getUserID() == userID) {
                        u.setStatus(false);
                        PublicEvent.getInstance().getEventMain().updateUser(u);
                        break;
                    }
                }
                if(msgMenuBtn.isSelected()) {
                    for(Component com : chatList.getComponents()) {
                        ChatLayout chat = (ChatLayout) com;
                        if(chat.getUser().getUserID() == userID) {
                            chat.updateStatus();
                            break;
                        }
                    }
                }
            }
            
        });
        showChats();
    }
    
    private void showChats() {
        chatList.removeAll();
        for(Model_User_Account d : userAccount)
        {
            chatList.add(new ChatLayout(null), "wrap");
        }
        refreshChatList();
    }

    private void showGroupChats() {
        chatList.removeAll();
        for(int i = 1; i <= 5; i++)
        {
            chatList.add(new ChatLayout(null), "wrap");
        }
        refreshChatList();
    }

    private void showCallLog() {
        chatList.removeAll();
        for(int i = 1; i < 10; i++)
        {
            chatList.add(new ChatLayout(null), "wrap");
        }
        refreshChatList();
    }

    private void refreshChatList() {
        chatList.repaint();
        chatList.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JLayeredPane();
        msgMenuBtn = new chatfusion.Chat.MenuButton();
        grpMenuBtn = new chatfusion.Chat.MenuButton();
        callMenuBtn = new chatfusion.Chat.MenuButton();
        scrollpane = new javax.swing.JScrollPane();
        chatList = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(204, 204, 255));

        menu.setOpaque(true);
        menu.setLayout(new javax.swing.BoxLayout(menu, javax.swing.BoxLayout.LINE_AXIS));

        msgMenuBtn.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/chatIcon.png"))); // NOI18N
        msgMenuBtn.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/chatIcon_simple.png"))); // NOI18N
        msgMenuBtn.setMaximumSize(new java.awt.Dimension(66, 66));
        msgMenuBtn.setSelected(true);
        msgMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgMenuBtnActionPerformed(evt);
            }
        });
        menu.add(msgMenuBtn);

        grpMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/group.png"))); // NOI18N
        grpMenuBtn.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/group_selected.png"))); // NOI18N
        grpMenuBtn.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/group.png"))); // NOI18N
        grpMenuBtn.setMaximumSize(new java.awt.Dimension(66, 66));
        grpMenuBtn.setMinimumSize(new java.awt.Dimension(43, 43));
        grpMenuBtn.setPreferredSize(new java.awt.Dimension(43, 43));
        grpMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpMenuBtnActionPerformed(evt);
            }
        });
        menu.add(grpMenuBtn);

        callMenuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/call.png"))); // NOI18N
        callMenuBtn.setIconSelected(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/call_selected.png"))); // NOI18N
        callMenuBtn.setIconSimple(new javax.swing.ImageIcon(getClass().getResource("/chatfusion/icon/call.png"))); // NOI18N
        callMenuBtn.setMaximumSize(new java.awt.Dimension(66, 66));
        callMenuBtn.setMinimumSize(new java.awt.Dimension(43, 43));
        callMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callMenuBtnActionPerformed(evt);
            }
        });
        menu.add(callMenuBtn);

        scrollpane.setBackground(new java.awt.Color(204, 204, 255));
        scrollpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chatList.setBackground(new java.awt.Color(204, 204, 255));
        chatList.setOpaque(true);

        javax.swing.GroupLayout chatListLayout = new javax.swing.GroupLayout(chatList);
        chatList.setLayout(chatListLayout);
        chatListLayout.setHorizontalGroup(
            chatListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chatListLayout.setVerticalGroup(
            chatListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        scrollpane.setViewportView(chatList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
            .addComponent(scrollpane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scrollpane)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void callMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if(!callMenuBtn.isSelected()) {
            msgMenuBtn.setSelected(false);
            grpMenuBtn.setSelected(false);
            callMenuBtn.setSelected(true);
            showCallLog();
        }
    }                                           

    private void msgMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if(!msgMenuBtn.isSelected()) {
            msgMenuBtn.setSelected(true);
            grpMenuBtn.setSelected(false);
            callMenuBtn.setSelected(false);
            showChats();
        }
    }                                          

    private void grpMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {
        if(!grpMenuBtn.isSelected()) {
            msgMenuBtn.setSelected(false);
            grpMenuBtn.setSelected(true);
            callMenuBtn.setSelected(false);
            showGroupChats();
        }
    }                                          


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chatfusion.Chat.MenuButton callMenuBtn;
    private javax.swing.JLayeredPane chatList;
    private chatfusion.Chat.MenuButton grpMenuBtn;
    private javax.swing.JLayeredPane menu;
    private chatfusion.Chat.MenuButton msgMenuBtn;
    private javax.swing.JScrollPane scrollpane;
    // End of variables declaration//GEN-END:variables
}
